---
version: "2.1"
services:
    snowpack:
      image: snowpackvipn/snowpack-user:latest
      container_name: snowpackuser
      environment:
      #Use your DarkSnow credentials
        USER : 'myusername'
        PASSWORD : 'Password1234'
        # List of possible args:
        #    -a for automatic route selection
        #    -r for manual route selection 
        # Refer to the README file for more options
        ADDITIONAL_ARGS: ' -a'
      volumes:
        - ./config_user_routes.json:/root/config_user_routes.json
      ports:
        - "6000:6000"
      privileged: true
      stdin_open: true
      tty: true

      healthcheck:
        test: sudo nft list ruleset | grep -q 'SNOWPACK';
        timeout: 30s
        interval: 1s
        retries: 3

    torbrowser-over-snowpack:
      build:
        context: .
        dockerfile: Dockerfile
      network_mode: service:snowpack
      environment:
        - DISPLAY=${DISPLAY}
        - WAYLAND_DISPLAY=${WAYLAND_DISPLAY} 
        #- UID=1000
        #- GID=1000 
      volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - ${XDG_RUNTIME_DIR}/wayland:/tmp/wayland
      stdin_open: true
      tty: true 
      user: "1000:1000" #Replace the value with your host's UID and GID user : "${UID}:${GID}"
