---
version: "3.8"
services:
    snowpackuser:
      image: snowpackvipn/snowpack-user:latest
      environment:
      #Replace your login credentials here! YOU NEED TO HAVE AT LEAST SUBSCRIBED TO A REDSNOW PLAN!
        USER: 'myusername' 
        PASSWORD: 'Password1234'
        # List of possible args:
        #    -a for automatic route selection
        #    -r for manual route selection 
        # Refer to the README file for more options
        ADDITIONAL_ARGS: ' -a'
      volumes:
        - ./config_user_routes.json:/root/config_user_routes.json
      container_name: snowpackuser
      ports:
        - "1080:1080" #Default port on which the socks proxy listen to
      privileged: true
      stdin_open: true
      tty: true

      healthcheck:
        test: sudo nft list ruleset | grep -q 'SNOWPACK';
        timeout: 30s
        interval: 1s
        retries: 3

    socks5:
      image: serjs/go-socks5-proxy
      container_name: socks5
      network_mode: service:snowpackuser #to force the socks5 proxy traffic to go through snowpack
